@props([
    'label',
    'name',
    'type' => 'text',
    'required' => false,
    'help' => null,
    'error' => null,
    'icon' => null,
    'placeholder' => null
])\n\n<div class=\"space-y-2\">\n    @if($label)\n        <label for=\"{{ $name }}\" class=\"form-label\">\n            {{ $label }}\n            @if($required)\n                <span class=\"text-danger-500 ml-1\">*</span>\n            @endif\n        </label>\n    @endif\n    \n    <div class=\"relative\">\n        @if($icon)\n            <div class=\"absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none\">\n                <div class=\"w-5 h-5 text-gray-400\">\n                    {!! $icon !!}\n                </div>\n            </div>\n        @endif\n        \n        @if($type === 'select')\n            <select \n                id=\"{{ $name }}\" \n                name=\"{{ $name }}\" \n                {{ $attributes->merge(['class' => 'form-select' . ($icon ? ' pl-12' : '') . ($error ? ' border-danger-300 focus:border-danger-500 focus:ring-danger-500/20' : '')]) }}\n                @if($required) required @endif\n            >\n                {{ $slot }}\n            </select>\n        @elseif($type === 'textarea')\n            <textarea \n                id=\"{{ $name }}\" \n                name=\"{{ $name }}\" \n                placeholder=\"{{ $placeholder }}\"\n                {{ $attributes->merge(['class' => 'form-input' . ($icon ? ' pl-12' : '') . ($error ? ' border-danger-300 focus:border-danger-500 focus:ring-danger-500/20' : ''), 'rows' => 4]) }}\n                @if($required) required @endif\n            >{{ $slot }}</textarea>\n        @else\n            <input \n                type=\"{{ $type }}\" \n                id=\"{{ $name }}\" \n                name=\"{{ $name }}\" \n                placeholder=\"{{ $placeholder }}\"\n                {{ $attributes->merge(['class' => 'form-input' . ($icon ? ' pl-12' : '') . ($error ? ' border-danger-300 focus:border-danger-500 focus:ring-danger-500/20' : '')]) }}\n                @if($required) required @endif\n            />\n        @endif\n    </div>\n    \n    @if($error)\n        <div class=\"form-error\">\n            <svg class=\"w-4 h-4\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z\"></path>\n            </svg>\n            {{ $error }}\n        </div>\n    @endif\n    \n    @if($help && !$error)\n        <div class=\"form-help\">\n            {{ $help }}\n        </div>\n    @endif\n</div>